### ISSUE TITLE
[Bug] Cropping the image leaves a white background, not the image itself [v0.2]

### ISSUE THREAD

**Issue by NEKolev** [OpenNumismat/ImageEditor#17]
A white background remains when manual cropping is used. I think the expected behavior is to leave only the cropped image with no background.

https://github.com/OpenNumismat/ImageEditor/assets/70388317/f906ab5b-c343-4dfd-a41f-3774bc61994e

**Comment by JanisV** [comment]
OpenNumismat uses the JPEG format to store images that do not support transparency. Added color selection for filling transparent areas

**Comment by JanisV** [comment]
Need to look into using WebP or avif format
