### ISSUE TITLE
[Bug] Incorrect closing of the program after editing [v0.3]

### ISSUE THREAD

**Issue by NEKolev** [OpenNumismat/ImageEditor#29]
When I have edited an image and close the program with X, a message appears from the program:
"---------------------------
Записване
---------------------------
Изображението е променено. Да се запазят ли промените?
---------------------------
Save   &No   
---------------------------"

To which I give **Save**. Then this message appears:

"---------------------------
Записване
---------------------------
Да се запазят ли промените в текущото изображение?
---------------------------
Save   &No   
---------------------------"

To which I give No and the program closes.

 The expected behavior is to open the screen where I can choose what to name the edited image and where to write.

**Comment by JanisV** [comment]
The second message is redundant
